### ISSUE TITLE
Flight date settings

### ISSUE THREAD

**Issue by joemidi** [google/dv360-write-api#12]
Hi there,

We are currently running a small two-day test in DV360 to see if our setup is working correctly. However, the script is now failing and I'm getting the below error in the logs.

```
Error: {
  "error": {
    "code": 400,
    "message": "When a flight/budget segment date is updated, the new value cannot be in the past.",
    "status": "INVALID_ARGUMENT"
  }
}
```

When I looked at the code I don't think we're updating the flight dates, only the Active/Paused status.

So is the error occurring because the flight end date is today (29/07/2021) and that is considered as "in the past" already?

**Comment by akushnarov** [comment]
Hi @joemidi,

sorry for the late reply, I saw this issue only couple of days ago. Next time I would  recommend to mention me in the conversation, so I receive a notification.

We haven't faced this particular issue before and it's impossible to reproduce for our accounts, so I'm going to close it. If it happens again please let me know.

Cheers
Andriy
